### ISSUE TITLE
Build break due to broken link in  ros_web_video/3rdparty/Makefile

### ISSUE THREAD

**Issue by sevenbitbyte** [RobotWebTools/ros_web_video#2]
The build currently fails due to a broken link in ros_web_video/3rdparty/Makefile which points to http://pr.willowgarage.com/downloads/.... An alternate source for this file is http://download.ros.org/downloads/ffmpeg_libvpx_3rdparty_sources.tar.gz

**Comment by rctoris** [comment]
Closing due to deprecation.
