### ISSUE TITLE
exported libary doesn't exist

### ISSUE THREAD

**Issue by dirk-thomas** [RobotWebTools/ros_web_video#8]
Where is the library `${PROJECT_NAME}` supposed to come from (https://github.com/RobotWebTools/ros_web_video/blob/2367baa20a471221a6e680c30dab771f92e0a0fd/CMakeLists.txt#L21)?

I would guess it needs to be removed from the catkin_package() call.

**Comment by rctoris** [comment]
Good catch. Not sure how that got in there. 

FYI this package has also been deprecated for https://github.com/RobotWebTools/web_video_server

**Comment by rctoris** [comment]
Closing due to deprecation.
